name: Metatheorem
markdown: redcarpet
highlighter: pygments
baseurl: /blog
permalink: :year/:month/:day/:title.html
collections:
  services:
    output: false
  pubs:
    output: false
gems:
  - jekyll-feed