name: Metatheorem
markdown: redcarpet
highlighter: pygments
permalink: /blog/blog/:year/:month/:day/:title.html
collections:
  services:
    output: false
  pubs:
    output: false
gems:
  - jekyll-feed