name: Metatheorem
highlighter: rouge
baseurl: /blog
permalink: :year/:month/:day/:title.html
collections:
  services:
    output: false
  pubs:
    output: false
gems:
  - jekyll-feed
theme: jekyll-theme-midnight
ncoding: utf-8